<#
.SYNOPSIS
Overview for Students:
This script represents Infrastructure as Code (IaC). Instead of manually clicking through a web interface to create dozens of folders (Safes) and assigning permissions to dozens of users, we define what the environment should look like in text arrays, and the script builds it exactly as defined.

Key Learning Concepts in this Script:

Data Matrices: Look at $SafesMatrix and $SafeMemberships. These are arrays of hashtables. They act as a configuration blueprint. If you want to add a new Safe to the environment, you don't write new code—you just add a new line to the matrix.
Role-Based Access Control (RBAC) Mapping: The $PermissionProfiles hashtable translates human-friendly roles (like "VaultAdmin" or "ConnectOnly") into the exact true/false API flags the PAM backend requires (like useAccounts=$true, deleteAccounts=$false).
The Execution Flow:
1. It reads the CSV file generated by Script 1 to know who is logging in.
2. It authenticates to the API.
3. It iterates through the $SafesMatrix to create the storage containers.
4. It iterates through the $SafeMemberships matrix to attach users and Active Directory groups to those Safes with precise permissions.
5. Least Privilege Cleanup: Finally, it removes the administrator account (the one running the script) from the Safes, ensuring that admins don't retain permanent backdoor access to secure vaults.
v26-9-01
#>

# Load the external library dynamically based on script location
$libraryPath = Join-Path -Path $PSScriptRoot -ChildPath "PAM_Library.ps1"
. $libraryPath


# Config
$global:EnableFileLogging = $true
$global:EnableDebugMode   = $false
$global:LogFilePath = Join-Path -Path ([Environment]::GetFolderPath("Desktop")) -ChildPath "PAM_Provisioning_$(Get-Date -Format 'yyyyMMdd_HHmmss').log"

# ==============================================================================
# Matrix Definitions
# ==============================================================================
$SafesMatrix = @(
    @{ safeName = "P-BOS-LIN-S-FIN"; description = "Linux Financial Servers"; numberOfDaysRetention = 5 }
    @{ safeName = "P-BOS-LIN-S-LOGON"; description = "Linux Logon Servers"; numberOfDaysRetention = 5 }
    @{ safeName = "P-BOS-DB-POS"; description = "POS Database Servers"; numberOfDaysRetention = 5 }
    @{ safeName = "P-BOS-Web-pgAdmin"; description = "pgAdmin Web Servers"; numberOfDaysRetention = 5 }
    @{ safeName = "P-BOS-WIN-S-LA-FIN"; description = "Windows LA Financial"; numberOfDaysRetention = 5 }
    @{ safeName = "P-BOS-WIN-DOM"; description = "Windows Domain Servers"; numberOfDaysRetention = 5 }
)

$SafeMemberships = @(
    @{ safeName = "P-BOS-LIN-S-FIN"; memberName = "LinuxAdmins@acme.corp"; memberType = "group"; profile = "ConnectAndViewMembers" }
    @{ safeName = "P-BOS-LIN-S-FIN"; memberName = "Privilege Cloud Administrators"; memberType = "Role"; profile = "VaultAdmin" }
    @{ safeName = "P-BOS-LIN-S-FIN"; memberName = "Safe Master"; memberType = "Role"; profile = "Full" }
    @{ safeName = "P-BOS-LIN-S-FIN"; memberName = "Privilege Cloud Safe Managers"; memberType = "Role"; profile = "Full" }

    @{ safeName = "P-BOS-LIN-S-LOGON"; memberName = "LinuxAdmins@acme.corp"; memberType = "group"; profile = "ConnectAndViewMembers" }
    @{ safeName = "P-BOS-LIN-S-LOGON"; memberName = "Privilege Cloud Administrators"; memberType = "Role"; profile = "VaultAdmin" }
    @{ safeName = "P-BOS-LIN-S-LOGON"; memberName = "Safe Master"; memberType = "Role"; profile = "Full" }
    @{ safeName = "P-BOS-LIN-S-LOGON"; memberName = "Privilege Cloud Safe Managers"; memberType = "Role"; profile = "Full" }
)

function New-PermSet ([string[]]$TruePerms) {
    $perms = @{ useAccounts=$false; retrieveAccounts=$false; listAccounts=$false; addAccounts=$false; updateAccountContent=$false; updateAccountProperties=$false; initiateCPMAccountManagementOperations=$false; specifyNextAccountContent=$false; renameAccounts=$false; deleteAccounts=$false; unlockAccounts=$false; manageSafe=$false; manageSafeMembers=$false; backupSafe=$false; viewAuditLog=$false; viewSafeMembers=$false; accessWithoutConfirmation=$false; createFolders=$false; deleteFolders=$false; moveAccountsAndFolders=$false; requestsAuthorizationLevel1=$false; requestsAuthorizationLevel2=$false }
    foreach ($p in $TruePerms) { $perms[$p] = $true }
    return $perms
}

$PermissionProfiles = @{
    "ConnectOnly" = New-PermSet -TruePerms @("listAccounts", "useAccounts")
    "ConnectAndViewMembers" = New-PermSet -TruePerms @("listAccounts", "useAccounts", "viewSafeMembers")
    "VaultAdmin" = New-PermSet -TruePerms @("listAccounts", "addAccounts", "updateAccountContent", "updateAccountProperties", "initiateCPMAccountManagementOperations", "specifyNextAccountContent", "renameAccounts", "deleteAccounts", "unlockAccounts", "viewSafeMembers", "viewAuditLog")
    "Full" = New-PermSet -TruePerms @("useAccounts", "retrieveAccounts", "listAccounts", "addAccounts", "updateAccountContent", "updateAccountProperties", "initiateCPMAccountManagementOperations", "specifyNextAccountContent", "renameAccounts", "deleteAccounts", "unlockAccounts", "manageSafe", "manageSafeMembers", "backupSafe", "viewAuditLog", "viewSafeMembers", "requestsAuthorizationLevel1", "accessWithoutConfirmation", "createFolders", "deleteFolders", "moveAccountsAndFolders")
}

# ==============================================================================
# Execution Flow
# ==============================================================================
try {
    Write-Log "--- Script Execution Started ---" -Level INFO
    Get-TenantAdminInfo

    Get-IdentityToken -Identity_Url $global:Identity_Url -UserEmail $global:AuthUser

    $DirectoryName = "Active Directory: acme.corp"
    Write-Log "Fetching Directory UUID for '$DirectoryName'..." -Level INFO
    $response = Invoke-RestMethod -Uri "$global:Identity_Url/Core/GetDirectoryServices" -Method POST -Headers $global:BaseHeaders -ContentType 'application/json'
    $DirectoryUuid = ($response.Result.Results | Where-Object { $_.Row.DisplayName -eq $DirectoryName }).Row.directoryServiceUuid

    if (-not $DirectoryUuid) { throw "Could not locate directory '$DirectoryName' in Identity platform." }
    Write-Log "Directory UUID: $DirectoryUuid" -Level SUCCESS

    New-PAMSafes -PAM_SaaS_Url $global:PAM_SaaS_Url -BaseHeaders $global:BaseHeaders -SafesMatrix $SafesMatrix

    Add-PAMSafeMembers -PAM_SaaS_Url $global:PAM_SaaS_Url -BaseHeaders $global:BaseHeaders -DirectoryUuid $DirectoryUuid -PermissionProfiles $PermissionProfiles -SafeMemberships $SafeMemberships

    #Remove-PAMSafeMember -PAM_SaaS_Url $global:PAM_SaaS_Url -BaseHeaders $global:BaseHeaders -SafesMatrix $SafesMatrix -MemberToRemove $global:AuthUser

    Write-Log "--- Script Execution Completed Successfully ---" -Level SUCCESS
} catch {
    Write-Log "Script execution halted due to a critical error: $($_.Exception.Message)" -Level ERROR
} finally {
    if ($global:BaseHeaders -and $global:BaseHeaders.ContainsKey("Authorization")) {
        Revoke-IdentityToken -Identity_Url $global:Identity_Url -BaseHeaders $global:BaseHeaders
    }
}
